# Generated by Django 5.0.6 on 2024-07-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='item/')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general_one', models.BooleanField(default=False)),
                ('is_general_two', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_photos', to='api.item')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_photo', to='api.photo')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='general_photo_one',
            field=models.OneToOneField(limit_choices_to={'is_general_one': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_general_photo_one', to='api.item_photos'),
        ),
        migrations.AddField(
            model_name='item',
            name='general_photo_two',
            field=models.OneToOneField(limit_choices_to={'is_general_two': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_general_photo_two', to='api.item_photos'),
        ),
    ]
