# Generated by Django 5.0.6 on 2024-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_color_size_itemstockss'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
