# Generated by Django 5.0.6 on 2024-07-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_general_photo_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='huy', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
