# Generated by Django 5.0.6 on 2024-07-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='confirm_password',
            new_name='passwordConfirmation',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='telephone',
            new_name='telNo',
        ),
    ]
