# Generated by Django 5.0.6 on 2024-07-06 22:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_remove_item_category_alter_item_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='temp-slug', editable=False, populate_from='name', unique=True),
        ),
    ]
