# Generated by Django 5.0.6 on 2024-07-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_color_item_remove_size_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_table',
            field=models.TextField(blank=True),
        ),
    ]
