# Generated by Django 5.0.6 on 2024-07-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='general_photo_one',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_general_one': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_general_photo_one', to='api.item_photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='general_photo_two',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_general_two': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_general_photo_two', to='api.item_photos'),
        ),
    ]
