# Generated by Django 5.0.6 on 2024-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_size_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelNoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('expires', models.DateTimeField()),
            ],
        ),
    ]
