# Generated by Django 5.0.6 on 2024-07-06 23:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='temp-slug', editable=False, populate_from='get_slug', unique=True),
        ),
    ]
