# Generated by Django 5.0.6 on 2024-07-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_telnocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelNoCode',
        ),
    ]
