# Generated by Django 5.0.6 on 2024-07-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_telnocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='item/'),
        ),
    ]
