# Generated by Django 5.0.6 on 2025-02-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.size'),
        ),
    ]
