# Generated by Django 5.0.6 on 2024-07-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1234-12-12 12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.frontenduser'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
