# Generated by Django 5.0.6 on 2024-07-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_color_item_remove_size_item'),
        ('authentication', '0001_initial'),
        ('purchases', '0003_alter_basketitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.frontenduser')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.favourites')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemstock')),
            ],
        ),
    ]
