# Generated by Django 5.0.6 on 2024-07-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_favourites_favouritesitem'),
        ('purchases', '0004_payment'),
    ]

    operations = [
    ]
