# Generated by Django 5.0.6 on 2024-07-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('purchases', '0005_merge_0004_favourites_favouritesitem_0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=79188942002, on_delete=django.db.models.deletion.CASCADE, to='authentication.frontenduser'),
            preserve_default=False,
        ),
    ]
