# Generated by Django 5.0.6 on 2024-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenduser',
            name='my_addreses',
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
