# Generated by Django 5.0.6 on 2024-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenduser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
