# Generated by Django 5.0.6 on 2024-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_telnocode_telno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telnocode',
            name='expires',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
