# Generated by Django 5.0.6 on 2024-07-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('purchases', '0006_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('received', 'Получен'), ('canceled', 'Отменен'), ('returned', 'Возвращен')], default='created', max_length=10),
        ),
    ]
