# Generated by Django 5.0.6 on 2024-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('received', 'Получен'), ('canceled', 'Отменен'), ('returned', 'Возвращен')], default='created', max_length=10),
        ),
    ]
